## Data Cleansing and Transformation

* Pembersihan data,
* penanganan data yang hilang,
* dan penerapan teknik transformasi untuk mencapai format data yang diinginkan.

In [1]:
!wget https://raw.githubusercontent.com/9uz/RPL23402/refs/heads/master/project/kode/hand_on_practice4/data/traffic_crash_people.csv
!wget https://github.com/9uz/RPL23402/blob/master/project/kode/hand_on_practice4/data/traffic_crash_vehicle.csv
!wget https://raw.githubusercontent.com/9uz/RPL23402/refs/heads/master/project/kode/hand_on_practice4/data/traffic_crashes.csv

--2026-05-07 06:08:58--  https://raw.githubusercontent.com/9uz/RPL23402/refs/heads/master/project/kode/hand_on_practice4/data/traffic_crash_people.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 354655 (346K) [text/plain]
Saving to: ‘traffic_crash_people.csv.1’

traffic_crash_peopl 100%[===================>] 346.34K  --.-KB/s    in 0.006s

2026-05-07 06:08:59 (61.1 MB/s) - ‘traffic_crash_people.csv.1’ saved [354655/354655]

--2026-05-07 06:08:59--  https://github.com/9uz/RPL23402/blob/master/project/kode/hand_on_practice4/data/traffic_crash_vehicle.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘traffic_crash_vehicle.csv.1’

traffic_crash_vehic     [ <=>                ]   2.54M  --.-KB/s    in 0.02s

2026-05-07 06:09:01 (127 MB/s) - ‘traffic_crash_vehicle.csv.1’ saved [2660869]

--2026-05-07 06:09:01--  https://raw.githubusercontent.com/9uz/RPL23402/refs/heads/master/project/kode/hand_on_practice4/data/traffic_crashes.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 629262 (615K) [text/plain]
Saving to: ‘traffic_crashes.csv.1’

traffic_crashes.csv 100%[===================>] 614.51K  --.-KB/s    in 0.005s

2026-05-07 06:09:01 (111 MB/s) - ‘traffic_crashes.csv.1’ saved [629262/629262]

In [2]:
# import modul
import pandas as pd

In [3]:

# masukkan lokasi data yang digunakan "traffic_crash dan traffic_crash_vehicle
traffic_crash = pd.read_csv("/content/traffic_crashes.csv")
traffic_crash_vehicle = pd.read_csv("/content/traffic_crash_vehicle.csv")
traffic_crash_people = pd.read_csv("/content/traffic_crash_people.csv")

In [ ]:
# import data as dataframes

## Tugas Awal: Pentingnya Staging data
Staging data (atau data staging) adalah tahap sementara dalam proses ETL (Extract, Transform, Load), di mana data mentah yang baru diambil dari sumbernya disimpan terlebih dahulu sebelum diproses lebih lanjut.

In [4]:
# tampilkan 10 data data traffic_crashes === .head() Fungsi untuk melihat data bagian atas / awal tabel 10 baris
traffic_crash.head(10)

,crash_record_id,rd_no,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048)
1,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288)
2,444221c2a9bc82fc4f301062ab22b482d7d661cf88fcdf...,JE494016,Y,2021-12-31T13:56:00.000,10,OTHER,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.722941,-87.662863,POINT (-87.662862871273 41.72294121821)
3,4603435fbb4ef5d45c0d805c3e9aa5558a311a140a737e...,JE494049,NaN,2021-12-31T13:46:00.000,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,PEDALCYCLIST,...,1.0,0.0,2.0,0.0,13,6,12,41.766336,-87.578270,POINT (-87.578269718478 41.766335621716)
4,db62bb4534d0dae57112ea3ff8d50193784aaa732ed58d...,JE494000,NaN,2021-12-31T13:45:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.751150,-87.607802,POINT (-87.607802036151 41.7511501753)
5,7be2d128e14efdcb70fdbf27dbe8fd18f31a045118f2b0...,JE493993,NaN,2021-12-31T13:40:00.000,30,STOP SIGN/FLASHER,FUNCTIONING PROPERLY,CLEAR,DAWN,REAR END,...,0.0,0.0,5.0,0.0,13,6,12,41.663254,-87.617789,POINT (-87.617788659925 41.663254478672)
6,b21c3c048ac319f0fca67804ab0fce0149c97d11a850ff...,JE494019,NaN,2021-12-31T13:31:00.000,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.869130,-87.680566,POINT (-87.680566016706 41.869130394922)
7,ff9ed4054cd9f4b2908d1e1ef79a4e70d752a0ba7907b2...,JF101317,NaN,2021-12-31T13:30:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,...,0.0,0.0,2.0,0.0,13,6,12,41.793226,-87.733024,POINT (-87.733024082995 41.793226012108)
8,0ff41d1ad3fb1e9bba0015c72222f5569df3b1254ce9d0...,JF100566,Y,2021-12-31T13:30:00.000,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,PARKED MOTOR VEHICLE,...,0.0,0.0,1.0,0.0,13,6,12,41.919623,-87.652345,POINT (-87.652345379655 41.919622612473)
9,77431b38762c7d632f83881886b3a1c94a52f6cb17ad6e...,JE494024,NaN,2021-12-31T13:30:00.000,15,UNKNOWN,UNKNOWN,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,...,0.0,0.0,1.0,0.0,13,6,12,41.684893,-87.663640,POINT (-87.663640292916 41.68489260582)

In [5]:
# info data data traffic_crashes ===== info(): Menampilkan jumlah baris dan kolom,nama kolom,tipe data tiap kolom,jumlah data yang tidak kosong (non-null)
traffic_crash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   object
 1   rd_no                          1000 non-null   object
 2   crash_date_est_i               69 non-null     object
 3   crash_date                     1000 non-null   object
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   object
 6   device_condition               1000 non-null   object
 7   weather_condition              1000 non-null   object
 8   lighting_condition             1000 non-null   object
 9   first_crash_type               1000 non-null   object
 10  trafficway_type                1000 non-null   object
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   object
 13  roadway_surface_cond           1000 non-null   object
 14  road_defect                    1000 non-null   object
 15  report_type                    976 non-null    object
 16  crash_type                     1000 non-null   object
 17  intersection_related_i         271 non-null    object
 18  private_property_i             45 non-null     object
 19  hit_and_run_i                  320 non-null    object
 20  damage                         1000 non-null   object
 21  date_police_notified           1000 non-null   object
 22  prim_contributory_cause        1000 non-null   object
 23  sec_contributory_cause         1000 non-null   object
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   object
 26  street_name                    1000 non-null   object
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     object
 29  statements_taken_i             22 non-null     object
 30  dooring_i                      0 non-null      float64
 31  work_zone_i                    4 non-null      object
 32  work_zone_type                 3 non-null      object
 33  workers_present_i              1 non-null      object
 34  num_units                      1000 non-null   int64
 35  most_severe_injury             998 non-null    object
 36  injuries_total                 998 non-null    float64
 37  injuries_fatal                 998 non-null    float64
 38  injuries_incapacitating        998 non-null    float64
 39  injuries_non_incapacitating    998 non-null    float64
 40  injuries_reported_not_evident  998 non-null    float64
 41  injuries_no_indication         998 non-null    float64
 42  injuries_unknown               998 non-null    float64
 43  crash_hour                     1000 non-null   int64
 44  crash_day_of_week              1000 non-null   int64
 45  crash_month                    1000 non-null   int64
 46  latitude                       987 non-null    float64
 47  longitude                      987 non-null    float64
 48  location                       987 non-null    object
dtypes: float64(11), int64(7), object(31)
memory usage: 382.9+ KB

In [6]:
# jumlahkan data traffic_crashes yang null
traffic_crash.isnull().sum()

crash_record_id                     0
rd_no                               0
crash_date_est_i                  931
crash_date                          0
posted_speed_limit                  0
traffic_control_device              0
device_condition                    0
weather_condition                   0
lighting_condition                  0
first_crash_type                    0
trafficway_type                     0
lane_cnt                          999
alignment                           0
roadway_surface_cond                0
road_defect                         0
report_type                        24
crash_type                          0
intersection_related_i            729
private_property_i                955
hit_and_run_i                     680
damage                              0
date_police_notified                0
prim_contributory_cause             0
sec_contributory_cause              0
street_no                           0
street_direction                    0
street_name                         0
beat_of_occurrence                  0
photos_taken_i                    985
statements_taken_i                978
dooring_i                        1000
work_zone_i                       996
work_zone_type                    997
workers_present_i                 999
num_units                           0
most_severe_injury                  2
injuries_total                      2
injuries_fatal                      2
injuries_incapacitating             2
injuries_non_incapacitating         2
injuries_reported_not_evident       2
injuries_no_indication              2
injuries_unknown                    2
crash_hour                          0
crash_day_of_week                   0
crash_month                         0
latitude                           13
longitude                          13
location                           13
dtype: int64

In [7]:
# hapus kolom data traffic_crashes yang bernilai null
data_penuh = traffic_crash.dropna(axis=1, inplace=False)
data_penuh.info()
clean_data = traffic_crash.drop(["dooring_i", "crash_date_est_i", "lane_cnt"],axis=1, inplace=False)
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   crash_record_id          1000 non-null   object
 1   rd_no                    1000 non-null   object
 2   crash_date               1000 non-null   object
 3   posted_speed_limit       1000 non-null   int64
 4   traffic_control_device   1000 non-null   object
 5   device_condition         1000 non-null   object
 6   weather_condition        1000 non-null   object
 7   lighting_condition       1000 non-null   object
 8   first_crash_type         1000 non-null   object
 9   trafficway_type          1000 non-null   object
 10  alignment                1000 non-null   object
 11  roadway_surface_cond     1000 non-null   object
 12  road_defect              1000 non-null   object
 13  crash_type               1000 non-null   object
 14  damage                   1000 non-null   object
 15  date_police_notified     1000 non-null   object
 16  prim_contributory_cause  1000 non-null   object
 17  sec_contributory_cause   1000 non-null   object
 18  street_no                1000 non-null   int64
 19  street_direction         1000 non-null   object
 20  street_name              1000 non-null   object
 21  beat_of_occurrence       1000 non-null   int64
 22  num_units                1000 non-null   int64
 23  crash_hour               1000 non-null   int64
 24  crash_day_of_week        1000 non-null   int64
 25  crash_month              1000 non-null   int64
dtypes: int64(7), object(19)
memory usage: 203.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   object
 1   rd_no                          1000 non-null   object
 2   crash_date                     1000 non-null   object
 3   posted_speed_limit             1000 non-null   int64
 4   traffic_control_device         1000 non-null   object
 5   device_condition               1000 non-null   object
 6   weather_condition              1000 non-null   object
 7   lighting_condition             1000 non-null   object
 8   first_crash_type               1000 non-null   object
 9   trafficway_type                1000 non-null   object
 10  alignment                      1000 non-null   object
 11  roadway_surface_cond           1000 non-null   object
 12  road_defect                    1000 non-null   object
 13  report_type                    976 non-null    object
 14  crash_type                     1000 non-null   object
 15  intersection_related_i         271 non-null    object
 16  private_property_i             45 non-null     object
 17  hit_and_run_i                  320 non-null    object
 18  damage                         1000 non-null   object
 19  date_police_notified           1000 non-null   object
 20  prim_contributory_cause        1000 non-null   object
 21  sec_contributory_cause         1000 non-null   object
 22  street_no                      1000 non-null   int64
 23  street_direction               1000 non-null   object
 24  street_name                    1000 non-null   object
 25  beat_of_occurrence             1000 non-null   int64
 26  photos_taken_i                 15 non-null     object
 27  statements_taken_i             22 non-null     object
 28  work_zone_i                    4 non-null      object
 29  work_zone_type                 3 non-null      object
 30  workers_present_i              1 non-null      object
 31  num_units                      1000 non-null   int64
 32  most_severe_injury             998 non-null    object
 33  injuries_total                 998 non-null    float64
 34  injuries_fatal                 998 non-null    float64
 35  injuries_incapacitating        998 non-null    float64
 36  injuries_non_incapacitating    998 non-null    float64
 37  injuries_reported_not_evident  998 non-null    float64
 38  injuries_no_indication         998 non-null    float64
 39  injuries_unknown               998 non-null    float64
 40  crash_hour                     1000 non-null   int64
 41  crash_day_of_week              1000 non-null   int64
 42  crash_month                    1000 non-null   int64
 43  latitude                       987 non-null    float64
 44  longitude                      987 non-null    float64
 45  location                       987 non-null    object
dtypes: float64(9), int64(7), object(30)
memory usage: 359.5+ KB

In [8]:
# "Hapus baris yang memiliki kurang dari 2 nilai non-NaN, sehingga hanya baris dengan minimal 2 nilai non-NaN yang tetap ada."
clean_data = traffic_crash.dropna(thresh=2, axis=0, inplace=False)
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   object
 1   rd_no                          1000 non-null   object
 2   crash_date_est_i               69 non-null     object
 3   crash_date                     1000 non-null   object
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   object
 6   device_condition               1000 non-null   object
 7   weather_condition              1000 non-null   object
 8   lighting_condition             1000 non-null   object
 9   first_crash_type               1000 non-null   object
 10  trafficway_type                1000 non-null   object
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   object
 13  roadway_surface_cond           1000 non-null   object
 14  road_defect                    1000 non-null   object
 15  report_type                    976 non-null    object
 16  crash_type                     1000 non-null   object
 17  intersection_related_i         271 non-null    object
 18  private_property_i             45 non-null     object
 19  hit_and_run_i                  320 non-null    object
 20  damage                         1000 non-null   object
 21  date_police_notified           1000 non-null   object
 22  prim_contributory_cause        1000 non-null   object
 23  sec_contributory_cause         1000 non-null   object
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   object
 26  street_name                    1000 non-null   object
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     object
 29  statements_taken_i             22 non-null     object
 30  dooring_i                      0 non-null      float64
 31  work_zone_i                    4 non-null      object
 32  work_zone_type                 3 non-null      object
 33  workers_present_i              1 non-null      object
 34  num_units                      1000 non-null   int64
 35  most_severe_injury             998 non-null    object
 36  injuries_total                 998 non-null    float64
 37  injuries_fatal                 998 non-null    float64
 38  injuries_incapacitating        998 non-null    float64
 39  injuries_non_incapacitating    998 non-null    float64
 40  injuries_reported_not_evident  998 non-null    float64
 41  injuries_no_indication         998 non-null    float64
 42  injuries_unknown               998 non-null    float64
 43  crash_hour                     1000 non-null   int64
 44  crash_day_of_week              1000 non-null   int64
 45  crash_month                    1000 non-null   int64
 46  latitude                       987 non-null    float64
 47  longitude                      987 non-null    float64
 48  location                       987 non-null    object
dtypes: float64(11), int64(7), object(31)
memory usage: 382.9+ KB

# Missing Data
report_type hanya mempunyai 2 isi, tampilkan dan ubah missing value menjadi "ON ..... "

https://pandas.pydata.org/pandas-docs/dev/user_guide/missing_data.html

In [9]:
# periksa isi yang ada pada kolom report_type pada data crash
traffic_crash["report_type"].unique()

array(['ON SCENE', 'NOT ON SCENE (DESK REPORT)', nan], dtype=object)

In [10]:
traffic_crash["report_type"].value_counts()

report_type
NOT ON SCENE (DESK REPORT)    499
ON SCENE                      477
Name: count, dtype: int64

In [11]:
# isi missing value dengan ddta " ..........."
traffic_crash["report_type"].fillna("ON SCENE", inplace=True)
traffic_crash["report_type"].value_counts()

/tmp/ipykernel_7755/1717597180.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  traffic_crash["report_type"].fillna("ON SCENE", inplace=True)

report_type
ON SCENE                      501
NOT ON SCENE (DESK REPORT)    499
Name: count, dtype: int64

# Merging Data

In [12]:
# gabungkan dataframe crash dan vehicle
df_gg = pd.merge(traffic_crash, traffic_crash_vehicle, on="crash_record_id")
df_gg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 120 entries, crash_record_id to hazmat_class
dtypes: float64(34), int64(9), object(77)
memory usage: 937.6+ KB

In [13]:
#tampilkan ukuran data
print(df_gg.shape)
print(len(df_gg))

(1000, 120)
1000

In [14]:
# tampilkan 5 sampel data
df_gg.sample(5)

,crash_record_id,rd_no_x,crash_date_est_i,crash_date_x,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
205,d6c9d5c52382e49df3ab10fbe4bae06e2d93ac38a28301...,JE493473,NaN,2021-12-30T23:47:00.000,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",PARKED MOTOR VEHICLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
855,05633d4a278b23ab3a162208c6e699d9234870a9236bbb...,JE492764,NaN,2021-12-29T14:10:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,65cdb5cf70120bad114e9487980d305e8bbbc56731114a...,JE491739,NaN,2021-12-29T10:31:00.000,10,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,5b0a89c702723d7a602c1bc38b5d8782d2f75d1bed3791...,JE493106,NaN,2021-12-30T13:15:00.000,30,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,PARKED MOTOR VEHICLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,4e592de79e9fc053f11795c71c5af0d72cc86e121fa033...,JE493876,NaN,2021-12-31T11:45:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLOUDY/OVERCAST,DAYLIGHT,ANGLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#Kelompokkan data berdasarkan kolom vehicle_type, lalu hitung jumlah crash_record_id untuk masing-masing jenis kendaraan. Tampilkan hasilnya dalam bentuk DataFrame yang terstruktur, dengan index yang sudah di-reset dala variabel (df_agg).
df_agg = df_gg.groupby("vehicle_type").agg({"crash_record_id": "count"}).reset_index()
print(df_agg)

                      vehicle_type  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA               89
12                    VAN/MINI-VAN               38

In [16]:
# Dari DataFrame hasil agregasi (df_agg), ambillah jumlah total kecelakaan yang melibatkan kendaraan bertipe 'PASSENGER' dan simpan ke dalam variabel number_of_passenger_cars_involved.
number_of_passenger_cars_involved = df_agg[df_agg["vehicle_type"] == "PASSENGER"]["crash_record_id"].values[0]
print(number_of_passenger_cars_involved)

633

# Mapping data target

In [17]:
# ubah kolom 'vehicle_type'menjadi'vehicletypes'
df_gg.rename(columns={"vehicle_type": "vehicletypes"}, inplace=True)
df_gg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 120 entries, crash_record_id to hazmat_class
dtypes: float64(34), int64(9), object(77)
memory usage: 937.6+ KB

# Fungsi Tranformasi
Buat fungsi untuk transformasi dengan isi meliputi
    # import data
    # hilangkan missing value
    # gabungkan data
    # transformasi kolom yang sesuai

In [ ]:
#buat fungsi
def tranform_data (crash_file,veliche_file) :





    return df_gg

In [ ]:
# jalankan fungsi

# Running the Workflow
Kode sebelumnya dapat dibagi menjadi fungsi yang dapat digunakan kembali dan mudah dikelola
1. fungsi untuk membaca data
2. fungsi untuk menhapus baris dengan nilai null
3. fungsi mengisi missing values
4. Fungsi gabung  2 data
5. fungsi rename kolom

In [ ]:
# 1. fungsi untuk membaca data

In [ ]:
# 2 fungsi untuk menhapus baris dengan nilai null

In [ ]:
# 3 fungsi mengisi missing value

In [ ]:
# 4 Fungsi untung menggabungkan 2 data

In [ ]:
# 5 Fungsi rename kolom

# Pipeline
Buat fungsi Fungsi Pipeline untuk menjalankan Fungsi Pembersihan dan Transformasi
1. pipeline baca data
2. pipeline hapus baris null
3. pipeline misssing values
4. pipeline merge data

In [ ]:
# 1 pipeline

In [ ]:
#

# Gunakan Data Lalu Lintas Chicago dan Jalankan Alur pipeline